name: multihugginggradio_env
channels:
  - defaults
dependencies:
  - pip:
    - accelerate==0.22.0
    - aiofiles==23.2.1
    - aiohttp==3.8.4
    - aiosignal==1.3.1
    - altair==5.0.1
    - annotated-types==0.5.0
    - async-timeout==4.0.2
    - attrs==22.2.0
    - charset-normalizer==3.0.1
    - click==8.1.7
    - contourpy==1.0.7
    - cycler==0.11.0
    - datasets==2.9.0
    - dill==0.3.6
    - einops==0.6.1
    - exceptiongroup==1.1.3
    - fastapi==0.103.0
    - ffmpy==0.3.1
    - filelock==3.9.0
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2023.1.0
    - gradio==3.41.2
    - gradio-client==0.5.0
    - h11==0.14.0
    - httpcore==0.17.3
    - httpx==0.24.1
    - huggingface-hub==0.16.4
    - importlib-resources==5.12.0
    - iniconfig==2.0.0
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - matplotlib==3.7.0
    - multidict==6.0.4
    - multiprocess==0.70.14
    - numpy==1.24.2
    - opencv-python==4.7.0.68
    - orjson==3.9.5
    - packaging==23.0
    - pandas==1.5.3
    - pillow==9.4.0
    - pluggy==1.3.0
    - pyarrow==11.0.0
    - pydantic==2.3.0
    - pydantic-core==2.6.3
    - pydub==0.25.1
    - pyparsing==3.0.9
    - pytest==7.4.0
    - python-multipart==0.0.6
    - pytz==2022.7.1
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - responses==0.18.0
    - scikit-learn==1.2.1
    - scipy==1.10.0
    - semantic-version==2.10.0
    - starlette==0.27.0
    - threadpoolctl==3.1.0
    - tokenizers==0.13.2
    - tomli==2.0.1
    - toolz==0.12.0
    - torch==1.13.1+cu116
    - torchaudio==0.13.1+cu116
    - torchvision==0.14.1+cu116
    - tqdm==4.64.1
    - transformers==4.26.1
    - typing-extensions==4.7.1
    - urllib3==1.26.14
    - uvicorn==0.23.2
    - websockets==11.0.3
    - xxhash==3.2.0
    - yarl==1.8.2
    - zipp==3.14.0
